name: build
on: [push, pull_request]
jobs:
  lint:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install flake8
      run: pip install flake8 flake8-import-order flake8-logging-format
    - name: Lint with flake8
      run: |
        flake8 --version
        flake8 --max-line-length=120
